export const REQUEST_FOLLOWING = 'REQUEST_FOLLOWING';
export const RECEIVE_FOLLOWING = 'RECEIVE_FOLLOWING';
export const COMPARE_FOLLOWING = 'COMPARE_FOLLOWING';
export const TWITTER_ERROR = 'TWITTER_ERROR';
